
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd-orchestrator

# Single control-plane node with high memory allocation
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        system-reserved: "memory=4Gi,cpu=2"
        kube-reserved: "memory=4Gi,cpu=2"
        eviction-hard: "memory.available<4Gi,nodefs.available<10%"
        max-pods: "200"
  extraPortMappings:
  - containerPort: 80
    hostPort: 30000
    protocol: TCP
  - containerPort: 443
    hostPort: 30001
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
  - containerPort: 3000
    hostPort: 3000
    protocol: TCP

# Enable feature gates for better performance
featureGates:
  PodPriority: true
  TaintBasedEvictions: true
  TaintNodesByCondition: true

# Configure cluster-wide settings
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      enable-admission-plugins: "NodeRestriction"
      max-requests-inflight: "2000"
      max-mutating-requests-inflight: "2000"
  scheduler:
    extraArgs:
      v: "2"
  controllerManager:
    extraArgs:
      v: "2" 