# Simple Test Deployment for Zorin Inc
# Using actual working Docker images for testing

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-test
  namespace: zorin-inc
  labels:
    app: user-service
    customer: zorin-inc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      containers:
      - name: user-service
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "user-service"
        - name: CUSTOMER
          value: "zorin-inc"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: zorin-inc
  labels:
    app: user-service
    customer: zorin-inc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-test
  namespace: zorin-inc
  labels:
    app: payment-service
    customer: zorin-inc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      containers:
      - name: payment-service
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "payment-service"
        - name: CUSTOMER
          value: "zorin-inc"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: zorin-inc
  labels:
    app: payment-service
    customer: zorin-inc
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: payment-service 