{{- if .Values.secrets }}
{{- range $secretName, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.customerId }}-{{ $secretName }}-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "customer-services.labels" $ | nindent 4 }}
    {{- include "customer-services.customerLabels" $ | nindent 4 }}
    secret-type: {{ $secretName }}
    customer: {{ $.Values.global.customerId }}
  annotations:
    orchestrator.rtte.com/customer-id: {{ $.Values.global.customerId }}
    orchestrator.rtte.com/secret-type: {{ $secretName }}
    orchestrator.rtte.com/secret-version: {{ $.Values.global.imageTag }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- if $secret.stringData }}
  {{- range $key, $value := $secret.stringData }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }} 